name: Send Email on Push

on:
  push:
    branches:
      - main  # adjust branch as needed

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          secure: true
          server_port: 465
          username: username #First part of Email before @
          from: from-email@gmail.com
          password: app-password-from-gmail
          subject: 'Code pushed to repository'
          body: |
            Someone has pushed code to the repository.
          to: to-email@gmail.com
